# Generated by Django 2.2.4 on 2019-09-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='SOLD', max_length=100)),
                ('issues', models.CharField(default='No issues', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Devices')),
            ],
            bases=('inventory.devices',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Devices')),
            ],
            bases=('inventory.devices',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Devices')),
            ],
            bases=('inventory.devices',),
        ),
    ]
